version: '3'
services:
  bd:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: brasileirao-sqlserver
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=some(!)Password